[package]
name = "liteyear"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
members = ["cargo-liteyear"]

[dependencies]
displaydoc = "0.2"
thiserror = "1.0"

[dependencies.liteyear-macro]
path = "macro"
